### PR TITLE
fix typo in function names (destory -> destroy)

### PR DESCRIPTION
**Pull request by jzern**

### CODE REVIEW

**Comment by jzern** [comment]
@yilun-zhangs please have a look.

**Review by yilun-zhangs — APPROVED** [review]
good to me

**Comment by jzern** [comment]
Thanks for the review. I don't have merge rights, if you do could you merge the change?

**Comment by yilun-zhangs** [comment]
> 



> Thanks for the review. I don't have merge rights, if you do could you merge the change?
I also don't have permission to merge, I will request administrator to help merge it.

**Comment by jzern** [comment]
@tammy-lees for approval

**Pull request merged**
